version: "3.9"
services:
  app:
    #build:
    #  dockerfile: Dockerfile
    #  context: .
    #  target: dev
    image: cosmtrek/air
    container_name: go-server
    working_dir: /server
    volumes:
      - .:/server
    env_file:
      - ./.env
    environment:
      GOFLAGS: "-buildvcs=false"
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres_db} #postgres_db
      POSTGRES_USER: ${POSTGRES_USER:-todoapp} #todoapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todoapp123} #todoapp123
      POSTGRES_DB: ${POSTGRES_DB:-todo} #todo
      POSTGRES_PORT: ${POSTGRES_PORT:-5432} #5432
    ports:
      - 8080:8080

  postgres_db:
    image: postgres:14-alpine
    container_name: postgres-db 
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-todoapp} #todoapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todoapp123} #todoapp123
      POSTGRES_DB: ${POSTGRES_DB:-todo} #todo
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
